In [48]:
import torch
import torch.nn as nn

In [49]:
# 宣言したnn.**にはランダムな初期値が格納されている
fc = nn.Linear(3, 2)

In [50]:
# manual_seed():乱数のシード値を固定する
torch.manual_seed(1)

In [51]:
print(fc.weight)
print(fc.bias)

Parameter containing:
tensor([[ 0.0285,  0.2109, -0.2250],
        [-0.0421, -0.0520,  0.0837]], requires_grad=True)
Parameter containing:
tensor([-0.0023,  0.5047], requires_grad=True)


In [52]:
x = torch.tensor([[1, 2, 3]], dtype=torch.float)

In [53]:
u = fc(x)

In [54]:
u

tensor([[-0.2271,  0.6097]], grad_fn=<AddmmBackward0>)

In [55]:
import torch.nn.functional as F

In [56]:
z = F.relu(u)
z

tensor([[0.0000, 0.6097]], grad_fn=<ReluBackward0>)

In [57]:
fc1 = nn.Linear(3, 2)
fc2 = nn.Linear(2, 1)

In [58]:
x = torch.tensor([[1, 2, 3]], dtype=torch.float32)
u1 = fc1(x)
z2 = F.relu(u1)
z2

tensor([[0.0000, 0.5164]], grad_fn=<ReluBackward0>)

In [59]:
y = fc2(z2)
y

tensor([[0.1514]], grad_fn=<AddmmBackward0>)

In [61]:
# 目標値
t = torch.tensor([[1]], dtype=torch.float)
t

tensor([[1.]])

In [62]:
loss = F.mse_loss(t, y)
loss

tensor(0.7201, grad_fn=<MseLossBackward0>)

nn : 調整すべきパラメータを持つ
F  : 調整すべきパラメータを持たない