In [8]:
import torch

x = torch.ones(5)  # input tensor
print("x\n", x)

y = torch.zeros(3)  # expected output
print("y\n", y)

w = torch.randn(5, 3, requires_grad=True)
print("w\n", w)

b = torch.randn(3, requires_grad=True)
print("b\n", b)

z = torch.matmul(x, w)+b
print("z\n", z)

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print("loss\n", loss)

x
 tensor([1., 1., 1., 1., 1.])
y
 tensor([0., 0., 0.])
w
 tensor([[-0.4972, -0.0772,  1.5887],
        [ 0.6711, -1.5223,  0.8504],
        [ 0.3846,  0.7639,  0.3122],
        [-0.3213, -0.3808, -0.0429],
        [ 0.4316,  0.6882,  0.2414]], requires_grad=True)
b
 tensor([-0.1511,  0.7399, -0.3804], requires_grad=True)
z
 tensor([0.5178, 0.2117, 2.5694], grad_fn=<AddBackward0>)
loss
 tensor(1.4777, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)


In [10]:
loss.backward()

In [11]:
w.grad

tensor([[0.2089, 0.1842, 0.3096],
        [0.2089, 0.1842, 0.3096],
        [0.2089, 0.1842, 0.3096],
        [0.2089, 0.1842, 0.3096],
        [0.2089, 0.1842, 0.3096]])

In [13]:
b.grad

tensor([0.2089, 0.1842, 0.3096])