In [1]:
from __future__ import print_function
import torch

In [9]:
x = torch.empty(5, 3)
x

tensor([[1.3553e-19, 1.3563e-19, 6.6070e-07],
        [2.6394e-06, 8.2991e-33, 1.3563e-19],
        [1.0658e-32, 1.3563e-19, 1.6114e-19],
        [3.0263e+29, 3.9174e-02, 4.7429e+30],
        [1.3494e+28, 2.9179e+32, 1.8465e+25]])

In [20]:
x = torch.rand(5, 3)
x

tensor([[0.9829, 0.5988, 0.2684],
        [0.5501, 0.9464, 0.5983],
        [0.4277, 0.5704, 0.1955],
        [0.9078, 0.4359, 0.7522],
        [0.1233, 0.7673, 0.6440]])

In [21]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [22]:
x.size()

torch.Size([5, 3])

In [23]:
type(x.size())

torch.Size

In [28]:
print(x)
y = torch.rand(5, 3)
print(y)
print(x + y)
print(torch.add(x, y))

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0.7246, 0.8322, 0.2938],
        [0.5843, 0.5014, 0.8009],
        [0.4770, 0.7284, 0.2872],
        [0.0862, 0.7621, 0.3253],
        [0.3365, 0.1197, 0.6760]])
tensor([[0.7246, 0.8322, 0.2938],
        [0.5843, 0.5014, 0.8009],
        [0.4770, 0.7284, 0.2872],
        [0.0862, 0.7621, 0.3253],
        [0.3365, 0.1197, 0.6760]])
tensor([[0.7246, 0.8322, 0.2938],
        [0.5843, 0.5014, 0.8009],
        [0.4770, 0.7284, 0.2872],
        [0.0862, 0.7621, 0.3253],
        [0.3365, 0.1197, 0.6760]])


In [30]:
result = torch.empty(5, 3)
# 引数outに出力先の変数をしていると代入してくれる
torch.add(x, y, out=result)
print(result)

tensor([[0.7246, 0.8322, 0.2938],
        [0.5843, 0.5014, 0.8009],
        [0.4770, 0.7284, 0.2872],
        [0.0862, 0.7621, 0.3253],
        [0.3365, 0.1197, 0.6760]])


In [31]:
# in-place処理
y.add_(x)
print(y)

tensor([[0.7246, 0.8322, 0.2938],
        [0.5843, 0.5014, 0.8009],
        [0.4770, 0.7284, 0.2872],
        [0.0862, 0.7621, 0.3253],
        [0.3365, 0.1197, 0.6760]])


In [35]:
print(y[3, ...])

tensor([0.0862, 0.7621, 0.3253])


In [36]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [39]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [40]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [42]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
