In [45]:
import torch

In [46]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [47]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [48]:
# grad_fn: 今の値になった演算子を求める
print(y.grad_fn)

In [49]:
z = y * y * 3
out = z.mean()

print(z, "\n", out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) 
 tensor(27., grad_fn=<MeanBackward0>)


In [50]:
out.backward()
print(out)
print(x.grad)

tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [58]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b)
print(b.grad_fn)
b.backward()
print(a.grad)

False
True
tensor(1127.2972, grad_fn=<SumBackward0>)
tensor([[-35.4828, -41.2753],
        [ 38.1970,  -9.3541]])


In [90]:
p = torch.ones(2, 2, requires_grad=True)
print(p)
q = p * 2
print(q)
r = q * 20
print(r)
out = r.sum()
print(out)
out.backward()
print(p.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)
tensor([[40., 40.],
        [40., 40.]], grad_fn=<MulBackward0>)
tensor(160., grad_fn=<SumBackward0>)
tensor([[40., 40.],
        [40., 40.]])
