In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [5]:
type(x_data)

torch.Tensor

In [7]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [10]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6805, 0.5927],
        [0.8235, 0.1104]])


In [22]:
shape = (2, 3,)

In [23]:
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8449, 0.8897, 0.7534],
        [0.1271, 0.7186, 0.5168]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
tensor = torch.ones(5, 5)
tensor.device

device(type='cpu')

In [56]:
tensor = torch.ones(4, 4)

ans = 0

for i in range(len(tensor)):
    for j in range(len(tensor[i])):
        tensor[i, j] = ans
        ans += 1

print(tensor)
print(tensor[:, 0])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
tensor([ 0.,  4.,  8., 12.])


In [62]:
t1 = torch.cat([tensor, tensor], dim=0)
t1

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [73]:
y1 = tensor @ tensor.T
print("tensor: \n", tensor)
print("tensor.T: \n", tensor.T)
print("tensor @ tensor.T: \n", y1)

z1 = tensor * tensor.T
print(z1)

tensor: 
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])
tensor.T: 
 tensor([[ 0.,  4.,  8., 12.],
        [ 1.,  5.,  9., 13.],
        [ 2.,  6., 10., 14.],
        [ 3.,  7., 11., 15.]])
tensor @ tensor.T: 
 tensor([[ 14.,  38.,  62.,  86.],
        [ 38., 126., 214., 302.],
        [ 62., 214., 366., 518.],
        [ 86., 302., 518., 734.]])
tensor([[  0.,   4.,  16.,  36.],
        [  4.,  25.,  54.,  91.],
        [ 16.,  54., 100., 154.],
        [ 36.,  91., 154., 225.]])


In [85]:
t = torch.ones(5)
print(f"t: {t}")
n = t.copy_(t)
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: tensor([1., 1., 1., 1., 1.])


In [83]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: tensor([2., 2., 2., 2., 2.])
